In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# notebook을 실행한 브라우저에서 바로 그림을 볼 수있게 해주는 명령어
# matplotlib 시각화 결과를 jupyter notebook에서 바로 확인하기 위한 코드 작성 
%matplotlib inline

In [2]:
# csv 파일 불러오기
# 파일 경로는 colab이용시 드라이브 경로, vsc이용시 로컬경로
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/google-app-pre.csv')

In [3]:
# 제대로 불러와졌는지 확인하고싶으면
print(data.shape) # 행, 열의 개수 확인 가능

(256596, 15)

In [4]:
data

,Unnamed: 0,App Name,App Id,Category,Rating,Maximum Installs,Free,Price,Currency,Released,Last Updated,Content Rating,Ad Supported,In App Purchases,Editors Choice
0,4,Neon 3d Iron Tech Keyboard Theme,com.ikeyboard.theme.neon_3d.iron.tech,Personalization,4.7,62433,True,0.0,USD,"Sep 22, 2019","Oct 07, 2020",Everyone,True,False,False
1,5,Caliway Conductor,com.caliwayconductor.driver,Travel & Local,3.7,42856,True,0.0,USD,"Sep 5, 2018","May 30, 2020",Everyone,False,False,False
2,9,REDMOND Robot,com.grit.redmond,Lifestyle,3.7,31235,True,0.0,USD,"Jul 1, 2020","May 26, 2021",Everyone,False,False,False
3,10,Coloring Book Barbaie,com.bisgumah.barbie,Entertainment,3.8,646456,True,0.0,USD,"Apr 21, 2019","Nov 13, 2020",Everyone,True,False,False
4,11,Random Number Generator,com.gary.randomnumber,Tools,4.2,21124,True,0.0,USD,"May 28, 2017","May 30, 2020",Everyone,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256591,873341,Aditivos Alimentarios,com.dac.codigose,Health & Fitness,4.6,47677,True,0.0,USD,"Jan 21, 2014","May 10, 2021",Everyone,True,False,False
256592,873349,FAIRTIQ,com.fairtiq.android,Maps & Navigation,4.2,317297,True,0.0,USD,"Apr 27, 2016","May 31, 2021",Everyone,False,False,False
256593,873356,Moneygment,ph.moneygment,Finance,2.0,187822,True,0.0,USD,"Oct 21, 2017","Jun 07, 2021",Everyone,False,False,False
256594,873357,La Sicilia Edicola Digitale,andr.lasicilia.agrigento,Entertainment,2.7,20415,True,0.0,USD,"Apr 16, 2015","Apr 06, 2020",Everyone,True,False,False
256595,873361,Driving Day,com.day.drivingday,Entertainment,2.8,590469,True,0.0,USD,"Jun 10, 2020","Jun 10, 2020",Everyone,True,False,False

In [5]:
#광고 있는 어플들 평점 순서대로
AdTrue =  data[data["Ad Supported"]== True].sort_values('Rating', ascending = False).reset_index(drop =False)

In [6]:
AdTrue

,index,Unnamed: 0,App Name,App Id,Category,Rating,Maximum Installs,Free,Price,Currency,Released,Last Updated,Content Rating,Ad Supported,In App Purchases,Editors Choice
0,24212,82220,Police Dog Robot Transform Game - Flying Car G...,com.grand.game.studio.police.dog.robot.transfo...,Weather,5.0,11086,True,0.0,USD,"Feb 20, 2021","Apr 02, 2021",Teen,True,False,False
1,252474,859290,ahad nama,com.ramikapp.ahad.nama,Books & Reference,5.0,11047,True,0.0,USD,"May 31, 2017","Jan 31, 2021",Everyone,True,False,False
2,57282,195740,Learn italian verbs,com.kbmobile.italian300words4,Education,5.0,10956,True,0.0,USD,"Sep 2, 2018","Feb 17, 2020",Everyone,True,True,False
3,152943,521298,US Army Special Forces Elite Commando Strike F...,com.zoombit.anti.terrorist.sniper.squad.shooting,Weather,5.0,12349,True,0.0,USD,"May 7, 2021","Jun 07, 2021",Teen,True,True,False
4,237533,808581,Wood Block Puzzle Sudoku 99,com.sonataee.woodblock.classicpuzzle.blockgame,Game,5.0,13066,True,0.0,USD,"Jan 31, 2021","May 17, 2021",Everyone,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174006,44289,150689,Voxify Pro,com.fyprox.voxifypro,Entertainment,1.0,152845,True,0.0,USD,"Apr 19, 2021","Apr 20, 2021",Everyone,True,False,False
174007,68316,232920,Live Face Camera Filter,com.photomakeup.live.face.camera.filters.effects,Photography,1.0,269301,True,0.0,USD,"Dec 14, 2017","Mar 14, 2019",Everyone,True,False,False
174008,192664,655919,NetCut 2021 Free WiFi Analyzer,com.fartosha.netcut_2021_free_wifi_analyzer,Productivity,1.0,73152,True,0.0,USD,"Sep 15, 2020","Oct 07, 2020",Everyone,True,False,False
174009,192634,655840,BEST HANDWRITING PRACTICE WITH DEMO,com.davardeepak.Best_Handwriting_practice_with...,Art & Design,1.0,18156,True,0.0,USD,"Jun 13, 2018","Jun 26, 2020",Everyone,True,False,False
174010,195521,665497,Jokes,com.abia.latestsms,Entertainment,1.0,147558,True,0.0,USD,"Jun 5, 2016","Mar 25, 2019",Everyone,True,False,False

In [7]:
#광고 있는 것 중 평점 5점짜리
AdTrue5 = AdTrue[AdTrue["Rating"] == 5].sort_values('Maximum Installs', ascending = False)

In [8]:
AdTrue5

,index,Unnamed: 0,App Name,App Id,Category,Rating,Maximum Installs,Free,Price,Currency,Released,Last Updated,Content Rating,Ad Supported,In App Purchases,Editors Choice
275,225834,768651,Photo Frame,com.highsecure.photoframe,Photography,5.0,35311430,True,0.0,USD,"Sep 21, 2016","May 21, 2021",Everyone,True,False,False
171,166306,566902,Maps Master for Minecraft,qtstudio.minecraft.modsinstaller,Entertainment,5.0,7247118,True,0.0,USD,"Nov 2, 2019","Dec 06, 2020",Everyone 10+,True,False,False
208,196546,668846,Music player,com.gspro.music.mp3player,Music & Audio,5.0,2160183,True,0.0,USD,"Apr 23, 2020","May 18, 2021",Everyone,True,False,False
113,30009,102039,Grand Speed Light Robot Battle,com.alpha.comic.grand.speedlight.robotcrime.ci...,Game,5.0,1965103,True,0.0,USD,"Dec 6, 2018","May 31, 2021",Teen,True,False,False
329,140419,478695,Policer - Men Women Police photo suit Editor Set,com.dsrtech.policer,Photography,5.0,1764086,True,0.0,USD,"Aug 17, 2018","Apr 30, 2021",Everyone,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,184921,629741,Puzzlejoy game Puzzle Collection,com.gamepuzzle.collection.puzzle,Game,5.0,10106,True,0.0,USD,"Oct 22, 2020","Jan 12, 2021",Everyone,True,False,False
135,217788,740889,Bubble Monkey Fruits,com.droidreborn.monkeyfruitbubbleshoot,Game,5.0,10094,True,0.0,USD,"Mar 25, 2020","Aug 13, 2020",Everyone,True,False,False
34,123046,419446,"FinInfo - Loans, Insurance, budgeting information",com.fininfo.finance.online,Finance,5.0,10039,True,0.0,USD,"May 14, 2020","Jun 24, 2020",Everyone,True,False,False
317,255278,868735,"Indian Bhabi Hot Video Chat, Hot girls chat",com.bhabhihotvideochathotgirlschat,Entertainment,5.0,10020,True,0.0,USD,"May 10, 2021","May 10, 2021",Mature 17+,True,False,False
263,113972,388563,Blue Dragon Launcher Theme,com.ansji.blue.dragon,Personalization,5.0,10001,True,0.0,USD,"May 5, 2021","May 05, 2021",Teen,True,False,False

In [9]:
#광고 있는 것 중 평점 5점짜리 카테고리 그룹화
ctg_ad5 = AdTrue5[data['Ad Supported'] == True].groupby('Category').count().sort_values('Category', ascending = False).reset_index(drop =False)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

In [10]:
ctg_ad5

,Category,index,Unnamed: 0,App Name,App Id,Rating,Maximum Installs,Free,Price,Currency,Released,Last Updated,Content Rating,Ad Supported,In App Purchases,Editors Choice
0,Weather,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18
1,Video Players & Editors,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
2,Travel & Local,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
3,Tools,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18
4,Social,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
5,Shopping,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
6,Productivity,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
7,Photography,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
8,Personalization,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30
9,News & Magazines,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
10,Music & Audio,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
11,Medical,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
12,Maps & Navigation,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
13,Lifestyle,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
14,Libraries & Demo,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
15,House & Home,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
16,Health & Fitness,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
17,Game,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63
18,Food & Drink,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
19,Finance,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
20,Events,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
21,Entertainment,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
22,Education,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
23,Dating,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
24,Communication,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
25,Comics,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
26,Business,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
27,Books & Reference,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20
28,Beauty,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
29,Art & Design,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6

In [11]:
#광고+5점 카테고리 데이터프레임 정리(인덱스만 담기)
ctg_ad5_c = ctg_ad5.drop(['Unnamed: 0', 'App Name',	'App Id',	'Rating',	'Maximum Installs',	'Free',	'Price',	'Currency',	'Released',	'Last Updated',	'Content Rating',	'Ad Supported',	'In App Purchases',	'Editors Choice'], axis=1).sort_values(by='index', ascending = False).reset_index(drop =True)

In [12]:
ctg_ad5_c

                   Category  index
0                      Game     63
1           Personalization     30
2         Books & Reference     20
3                   Weather     18
4                     Tools     18
5             Entertainment     17
6                 Education     14
7                 Lifestyle     10
8             Music & Audio      8
9            Travel & Local      7
10              Photography      7
11             Art & Design      6
12  Video Players & Editors      5
13             Productivity      4
14                   Social      4
15                 Business      3
16            Communication      3
17                   Events      2
18                   Dating      2
19             House & Home      2
20         Health & Fitness      2
21                  Finance      1
22                  Medical      1
23                 Shopping      1
24             Food & Drink      1
25         News & Magazines      1
26                   Comics      1
27         Libraries & Demo      1
28                   Beauty      1
29        Maps & Navigation      1

In [13]:
#광고 있고 평점 5점 다운로드수로 정렬
MI_ad5 = AdTrue5.drop(['Unnamed: 0', 'App Id',	'Rating',	'Free',	'Price', 'index', 'Currency',	'Released',	'Last Updated',	'Content Rating',	'Ad Supported',	'In App Purchases',	'Editors Choice'], axis=1).reset_index(drop =True)

In [14]:
#광고 있고 평점 5점 다운로드수 상위 10개 중 인앱 구매가 6개, 상위 20개 중에 인앱 구매가 7개
MI_ad5.head(30)

,App Name,Category,Maximum Installs
0,Photo Frame,Photography,35311430
1,Maps Master for Minecraft,Entertainment,7247118
2,Music player,Music & Audio,2160183
3,Grand Speed Light Robot Battle,Game,1965103
4,Policer - Men Women Police photo suit Editor Set,Photography,1764086
5,Pencil draw puzzle - draw one part,Game,1500447
6,"Punjabi Status, Punjabi Song clips, Punjabi vi...",Entertainment,1267301
7,"Photo frame, Photo collage",Photography,1241767
8,Real Police Car Parking Challenge Game 2020,Game,1047982
9,Snow Excavator Crane Simulator,Travel & Local,1037853
10,Car Wash Service Truck Games - Car Mechanic 3D,Weather,905182
11,Stickman Offroad Transporter Truck Cargo,Libraries & Demo,875766
12,Go Advance Translator,Books & Reference,745092
13,Donut Stack,Game,605773
14,Dog Robot Transform Moto Robot Transformation ...,Weather,602512
15,Live Face Sticker Sweet Camera,Beauty,530280
16,US Police Transform Tank Robot War,Lifestyle,500829
17,Sholawat Nissa Sabyan Offline,Music & Audio,470962
18,Biryani Cooking Indian Super Chef Food Game,Game,464306
19,Jigsaw Kingdoms - puzzle game,Game,440938
20,Turkish Flag Wallpapers 4K HD,Personalization,404053
21,Capsa Susun,Game,344059
22,SmartPharma,Medical,301100
23,Japan train card balance check,Tools,295433
24,Hang Climb Adventure-Grand Mountain Climber,Game,291975
25,Valentine Day Photo Frame,Photography,283710
26,Offroad Desert Prado Game 4x4 Jeep Rally simul...,Game,246279
27,French Good morning Goodnight Love Messages,Social,237553
28,Endless Temple Castle Oz Run,Game,232138
29,Firefighter Truck Rescue Drive Hero,Game,223782

In [15]:
#광고 있고 평점 5점 인앱 구매 있음 87개
#게임이 23개로 압도적으로 많음
AdInAppT = AdTrue5[AdTrue5["In App Purchases"] == True].drop(['Unnamed: 0',	'App Id',	'Rating',		'Free',	'Price',	'Currency',	'Released',	'Last Updated',	'Content Rating',	'Ad Supported',	'In App Purchases',	'Editors Choice', 'index'], axis=1).sort_values(by='Maximum Installs', ascending = False).reset_index(drop = True)

In [16]:
AdInAppT

,App Name,Category,Maximum Installs
0,Pencil draw puzzle - draw one part,Game,1500447
1,Real Police Car Parking Challenge Game 2020,Game,1047982
2,Snow Excavator Crane Simulator,Travel & Local,1037853
3,Stickman Offroad Transporter Truck Cargo,Libraries & Demo,875766
4,Donut Stack,Game,605773
...,...,...,...
82,Grand Robot Tank Transform War,Weather,11015
83,Learn italian verbs,Education,10956
84,Ant Hit,Game,10918
85,Learn italian offline,Education,10889
86,Tailor Pro,Productivity,10393

In [17]:
#광고 있고 평점 5점 인앱 구매 없음 296개
AdInAppF = AdTrue5[AdTrue5["In App Purchases"] == False].drop(['Unnamed: 0',	'App Id',	'Rating',		'Free',	'Price',	'Currency',	'Released',	'Last Updated',	'Content Rating',	'Ad Supported',	'In App Purchases',	'Editors Choice', 'index'], axis=1).sort_values(by='Maximum Installs', ascending = False).reset_index(drop = True)

In [18]:
AdInAppF

,App Name,Category,Maximum Installs
0,Photo Frame,Photography,35311430
1,Maps Master for Minecraft,Entertainment,7247118
2,Music player,Music & Audio,2160183
3,Grand Speed Light Robot Battle,Game,1965103
4,Policer - Men Women Police photo suit Editor Set,Photography,1764086
...,...,...,...
291,Puzzlejoy game Puzzle Collection,Game,10106
292,Bubble Monkey Fruits,Game,10094
293,"FinInfo - Loans, Insurance, budgeting information",Finance,10039
294,"Indian Bhabi Hot Video Chat, Hot girls chat",Entertainment,10020
295,Blue Dragon Launcher Theme,Personalization,10001

In [19]:
#인앱구매 있는거 카테고리 수
AdInAppTC= AdInAppT[data['Ad Supported'] == True].drop(['Maximum Installs'], axis=1).groupby('Category').count().sort_values('App Name', ascending = False).reset_index(drop =False)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

In [20]:
AdInAppTC

             Category  App Name
0                Game        24
1             Weather        10
2      Travel & Local         6
3           Education         4
4               Tools         3
5    Libraries & Demo         2
6        Productivity         2
7              Social         2
8   Books & Reference         1
9              Comics         1
10      Communication         1
11          Lifestyle         1
12  Maps & Navigation         1

In [21]:
#인앱구매 없는거 카테고리 수
AdInAppFC= AdInAppF[data['Ad Supported'] == True].drop(['Maximum Installs'], axis=1).groupby('Category').count().sort_values('App Name', ascending = False).reset_index(drop = False)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

In [22]:
AdInAppFC

                   Category  App Name
0                      Game        37
1           Personalization        25
2         Books & Reference        20
3             Entertainment        16
4                     Tools        15
5                 Education        10
6             Music & Audio         9
7                   Weather         8
8                 Lifestyle         8
9               Photography         7
10  Video Players & Editors         5
11             Art & Design         5
12                   Dating         5
13            Communication         5
14             Productivity         4
15                   Social         4
16                  Medical         3
17                 Business         3
18         Health & Fitness         2
19           Travel & Local         2
20             House & Home         2
21             Food & Drink         1
22                   Beauty         1
23                  Finance         1
24                   Events         1
25         News & Magazines         1
26                Parenting         1
27                   Comics         1

카테고리별 인앱 구매 유무 개수

카테고리 이름 / 총 개수() / 인앱구매 F(296) / 인앱구매 T(87)
Game 63 40 23
personalization 30 30 0
Books & Reference	20 19 1
Weather	18 10 8
Tools	18 16 2
Entertainment	17 17 0
Education	14 11 3
Lifestyle	10 9 1
Music & Audio	8 8 0
Travel & Local	7 1 6
Photography	7 7 0
Art & Design	6 6 0
Video Players & Editors	5 5 0
Productivity	4 3 1 
Social	4 3 1
Business	3 3 0
Communication	3 2 1
Events	2 2 0
Dating	2 2 0
House & Home	2 2 0
Health & Fitness	2 2 0
Finance	1 1 0
Medical	1 1 0
Shopping	1 1 0
Food & Drink	1 1 0
News & Magazines	1 1 0
Comics	1 0 1
Libraries & Demo	1 0 1
Beauty	1 1 0
Maps & Navigation	1 1 0

In [23]:
ctg_ad5_c

                   Category  index
0                      Game     63
1           Personalization     30
2         Books & Reference     20
3                   Weather     18
4                     Tools     18
5             Entertainment     17
6                 Education     14
7                 Lifestyle     10
8             Music & Audio      8
9            Travel & Local      7
10              Photography      7
11             Art & Design      6
12  Video Players & Editors      5
13             Productivity      4
14                   Social      4
15                 Business      3
16            Communication      3
17                   Events      2
18                   Dating      2
19             House & Home      2
20         Health & Fitness      2
21                  Finance      1
22                  Medical      1
23                 Shopping      1
24             Food & Drink      1
25         News & Magazines      1
26                   Comics      1
27         Libraries & Demo      1
28                   Beauty      1
29        Maps & Navigation      1

In [24]:
AdTrue5.loc[275]

index                                  225834
Unnamed: 0                             768651
App Name                          Photo Frame
App Id              com.highsecure.photoframe
Category                          Photography
Rating                                    5.0
Maximum Installs                     35311430
Free                                     True
Price                                     0.0
Currency                                  USD
Released                         Sep 21, 2016
Last Updated                     May 21, 2021
Content Rating                       Everyone
Ad Supported                             True
In App Purchases                        False
Editors Choice                          False
Name: 275, dtype: object